# Generated by Django 4.0.6 on 2022-08-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
