# Generated by Django 4.0.6 on 2022-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEapicrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
