# Generated by Django 3.2.15 on 2022-08-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('last_name', models.CharField(default=0, max_length=1000)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
