# Generated by Django 3.2.15 on 2022-08-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220818_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
